matlabbatch{1}.spm.meeg.source.simulate.D = '<UNDEFINED>';
matlabbatch{1}.spm.meeg.source.simulate.val = 1;
matlabbatch{1}.spm.meeg.source.simulate.prefix = '<UNDEFINED>';
matlabbatch{1}.spm.meeg.source.simulate.whatconditions.condlabel = {'Left_Long'};
matlabbatch{1}.spm.meeg.source.simulate.isinversion.setsources.woi = [100 400];
matlabbatch{1}.spm.meeg.source.simulate.isinversion.setsources.isSin.foi = 20;
matlabbatch{1}.spm.meeg.source.simulate.isinversion.setsources.dipmom = '<UNDEFINED>';
matlabbatch{1}.spm.meeg.source.simulate.isinversion.setsources.locs = '<UNDEFINED>';
matlabbatch{1}.spm.meeg.source.simulate.isSNR.setSNR = '<UNDEFINED>';
